#+TITLE: cl-electron - Electron binding for Common Lisp

* Installation
=cl-electron= depends on Electron, NodeJS, a Common Lisp implementation
(SBCL) and some CL libraries (consult [[file:cl-electron.asd][cl-electron.asd file]]).

** Nix + Quicklisp
Issuing =nix-shell= at the root of the project starts an environment
where all dependencies are available except for the CL libraries.

If you manage CL libraries by yourself, place them in a directory where
ASDF finds them (e.g. =~/common-lisp/=).

If you manage Common Lisp dependencies with Quicklisp:

1. Clone the git repository to =~/common-lisp/quicklisp/local-projects/cl-electron=
2. =sbcl=
3. =(ql:quickload :cl-electron)=

** Guix
Electron can only be fetched from the =nonguix= channel.  Add the
channel by editing the file =~/.config/guix/channels.scm=, according to
the example below.

#+begin_src scheme
(cons* (channel
        (name 'nonguix)
        (url "https://gitlab.com/nonguix/nonguix")
        (introduction
         (make-channel-introduction
          "897c1a470da759236cc11798f4e0a5f7d4d59fbc"
          (openpgp-fingerprint
           "2A39 3FFF 68F4 EF7A 3D29  12AF 6F51 20A0 22FB B2D5"))))
       %default-channels)
#+end_src

Start a REPL with all the dependencies by issuing:

=guix shell -D -f /path/to/guix.scm -- sbcl=.

* Example
In the example below we launch Electron to create a window that handles
on key press events.

#+begin_src lisp
  (asdf:load-system :cl-electron)
  (defvar my-interface (make-instance 'electron:interface
                                      :electron-socket-path (uiop:xdg-runtime-dir "electron.socket")
                                      :lisp-socket-path (uiop:xdg-runtime-dir "lisp.socket")))
  (electron:launch my-interface)
  (electron::register-before-input-event
   (make-instance 'electron:browser-window :interface my-interface)
   (lambda (browser-window input) (print input)))
#+end_src

* Copying
cl-electron is distributed under the BSD license.

Please note that this license only covers the binding itself. Refer to
the distribution terms of the third-party dependencies for details.
